apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-helloworld
  labels:
    app: docker-helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-helloworld
  template:
    metadata:
      labels:
        app: docker-helloworld
    spec:
      containers:
      - name: docker-helloworld-container
        image: deepansh257/hello-world-docker-basics:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/e2e-az-name
                operator: In
                values:
                - az1
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "day1"
        effect: "NoSchedule"
